baseURL: "https://www.ezequielcardoso.com"
languageCode: "es-ar"
title: "Ezequiel Cardoso"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-1FJ911SBK5

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:


  title: "Ezequiel Cardoso"
  description: I'm learning PHP
  # staticPath: ""  # The path to serve the static files from
  favicon: "/code2.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ezequiel."
    subtitle: "And i like to program in PHP"
    content: "A year and a half ago I decided to start studying web development. I started out learning front-end development until php came my way."
    image: /images/toonme2.jpg
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1q4KFhtVpQvFRx46ct4SdGIlu4PpLgMnD/view?usp=sharing"
      download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/cardosoe
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/ezequielcardoso/
          customIcons:
        - icon: fab fa-discord
          url: https://discordapp.com/users/#5737
          customIcons:
        - icon: fab fa-dev
          url: https://dev.to/eze_cardoso
          customIcons:

  # About
  about:
    enable: true
    title: "About me"
    image: "/images/cartoon.jpg"
    content: |-
      I am a software developer with a passion for web development and tech in general. I have a strong interest in technology and commerce topics related. I am looking actively for working opportunities. 

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "PHP"
        - "Laravel"
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Mysql"
        - "Sass"
        - "Bootstrap"

  # Experience
  # experience:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - job: "Senior Software Developer"
  #       company: "Facebook"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2022 - present"
  #       featuredLink:
  #         enable: true
  #         name: "View the project"
  #         url: "https://example.com"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  #     - job: "Software Developer"
  #       company: "Amazon"
  #       companyUrl: "https://example.com"
  #       date: "Sep 2020 - Dec 2021"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       info:
  #         enable: true
  #         content: I worked as a software developer for more than one year in Amazon.
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "Junior Software Developer"
  #       company: "Apple"
  #       companyUrl: "https://example.com"
  #       date: "Jan 2020 - Aug 2020"
  #       info:
  #         enable: false
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "UI/UX Designer"
  #       company: "Netflix"
  #       companyUrl: "https://example.com"
  #       date: "June 2017 - Nov 2019"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "Product Designer"
  #       company: "Google"
  #       companyUrl: "https://example.com"
  #       date: "Feb 2016 - Mar 2017"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  # education:
  #   enable: true
    # title: "Custom Name"
    # index: true
    # items:
    #   - title: "Master of Business Administration"
    #     school:
    #       name: "University of California, Berkeley"
    #       url: "https://example.org"
    #     date: "2013 - 2015"
    #     GPA: "3.8 out of 5.0"
    #     content: |-
    #       Extracurricular Activities
    #         - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
    #         - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
    #   - title: "Bachelor of Science in Computer Science"
    #     school:
    #       name: "Massachusetts Institute of Technology"
    #       url: "https://example.org"
    #     date: "2009 - 2013"
    #     GPA: "3.9 out of 5.0"
    #     content: |-
    #       I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
    #       - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
    #       - Face mask detection using a single convolutional neural network.

    #       Extracurricular Activities
    #         - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
    #         - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
    #     featuredLink:
    #       enable: true
    #       name: "My academic record"
    #       url: "https://example.com"
    #   - title: "High School"
    #     school:
    #       name: "Thomas Jefferson High School for Science and Technology."
    #       url: "https://example.org"
    #     GPA: "4.2 out of 5.0"
    #     featuredLink:
    #       enable: true
    #       url: "https://example.com"

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Landing Page 
        content: React & Laravel landing page.
        image: /images/projects/landingPage25whatts.jpg
        featured:
          name: Demo
          link: https://landing25whattsfront.herokuapp.com/
        badges:
          - "Html"
          - "Css"
          - "Sass"
          - "React"
        links:
          - icon: fab fa-github
            url: https://github.com/cardosoe/Proyecto-Integrador

      - title: Landing Page 
        content: Backend project for a React landing page.
        image: /images/projects/backendProject.jpg
        featured:
          name: Demo
          link: https://landing25whattsfront.herokuapp.com/
        badges:
          - "Laravel"
          - "MySql"
        links:
          - icon: fab fa-github
            url: https://github.com/cardosoe/backend_project


      - title: MornMeetTraining 
        content: Website created to organize training groups consuming data from a Database build in Firebase.
        image: /images/projects/mornmeet.jpg
        featured:
          name: Demo
          link: https://mornmeet-training.netlify.app/
        badges:
          - "Html"
          - "Css"
          - "JavaScript"
          - "Saas"
          - "Firebase"
        links:
          - icon: fab fa-github
            url: https://github.com/frontendcafe/cmyk-morning


      - title: Pokemon Hangman game
        content: Basic Hangman game written in PHP to be run in the terminal.
        image: https://commons.wikimedia.org/wiki/File:Hangman_game.jpg
        featured:
          name: Demo
          link:
        badges:
          - "PHP"
        links:
          - icon: fab fa-github
            url: https://github.com/cardosoe/php_hangman
  #Contact
  contact:
    enable: true
    #title: "Custom name"
    content: My inbox is always open. Whether you have a question, proposal or just want to say hi, Iâ€™ll try my best to get back to you!
    email: ezequielcardoso@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/cardosoe
      linkedin: https://linkedin.com/in/ezequielcardoso/
     
